name: code-review
on: [pull_request]

jobs:
  detekt:
    name: Check Code Quality
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Clone repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          ref: ${{ github.head_ref }}
      - name: detekt
        uses: alaegin/Detekt-Action@v1.18.1.2
        with:
          github_token: ${{ secrets.github_token }}
          detekt_config: detekt.yml